<?php


return [
    'views' => [],
    'types' => [],
    'icons' => [
        'heart',
        'sparkles',
        'calendar-days',
        'map-pin',
        'gift',
        'shopping-bag',
        'musical-note',
        'users',
        'bus',
        'car',
        'information-circle',
        'check-circle',
        'store',
        'bike',
        'waves',
        'music',
        'palette',
        'utensils',
        'smile',
        'heart-handshake',
        'coffee',
        'shirt',
        'gem',
        'book-open',
        'apple',
        'clock',
        'map',
        'paw-print',
        'trees',
        'sun',
        'umbrella',
        'train',
        'taxi',
        'parking-circle',
    ],
];
